project_name: coffee-bot

project_path: /opt/coffee-bot

venv_path: /opt/coffee-bot/.venv

python_bin: /usr/bin/python3

bot_user: ubuntu

bot_group: ubuntu

default_place: "Мега"

default_time: "21:00"
